import type { NextConfig } from "next";

const routeAliases = [
  ["/login", "/Auth/Login"],
  ["/forgot-password", "/Auth/ForgotPassword"],
  ["/reset-password", "/Auth/ResetPassword"],
  ["/unauthorized", "/Unauthorized"],

  ["/admin", "/Dashboards/Admin"],
  ["/admin/students", "/Dashboards/Admin/Students"],
  ["/admin/students/new", "/Dashboards/Admin/Students/New"],
  ["/admin/students/:studentId/edit", "/Dashboards/Admin/Students/:studentId/Edit"],
  ["/admin/students/:studentId", "/Dashboards/Admin/Students/:studentId"],
  ["/admin/rfid-cards", "/Dashboards/Admin/RfidCards"],
  ["/admin/rfid-cards/register", "/Dashboards/Admin/RfidCards/Register"],
  ["/admin/rfid-cards/:cardId", "/Dashboards/Admin/RfidCards/:cardId"],
  ["/admin/live-monitoring", "/Dashboards/Admin/LiveMonitoring"],
  ["/admin/attendance", "/Dashboards/Admin/Attendance"],
  ["/admin/attendance/:attendanceId", "/Dashboards/Admin/Attendance/:attendanceId"],
  ["/admin/sms-notifications", "/Dashboards/Admin/SmsNotifications"],
  ["/admin/sms-notifications/:smsLogId", "/Dashboards/Admin/SmsNotifications/:smsLogId"],
  ["/admin/reports", "/Dashboards/Admin/Reports"],
  ["/admin/users", "/Dashboards/Admin/Users"],
  ["/admin/users/new", "/Dashboards/Admin/Users/New"],
  ["/admin/users/:userId/edit", "/Dashboards/Admin/Users/:userId/Edit"],
  ["/admin/users/:userId", "/Dashboards/Admin/Users/:userId"],
  ["/admin/announcements", "/Dashboards/Admin/Announcements"],
  ["/admin/announcements/new", "/Dashboards/Admin/Announcements/New"],
  ["/admin/announcements/:announcementId/edit", "/Dashboards/Admin/Announcements/:announcementId/Edit"],
  ["/admin/correction-requests", "/Dashboards/Admin/CorrectionRequests"],
  ["/admin/correction-requests/:requestId", "/Dashboards/Admin/CorrectionRequests/:requestId"],
  ["/admin/notifications", "/Dashboards/Admin/Notifications"],
  ["/admin/audit-logs", "/Dashboards/Admin/AuditLogs"],
  ["/admin/device-monitoring", "/Dashboards/Admin/DeviceMonitoring"],
  ["/admin/device-monitoring/:deviceId", "/Dashboards/Admin/DeviceMonitoring/:deviceId"],
  ["/admin/settings", "/Dashboards/Admin/Settings"],

  ["/teacher", "/Dashboards/Teacher"],
  ["/teacher/my-students", "/Dashboards/Teacher/MyStudents"],
  ["/teacher/my-students/:studentId", "/Dashboards/Teacher/MyStudents/:studentId"],
  ["/teacher/attendance", "/Dashboards/Teacher/Attendance"],
  ["/teacher/attendance/:attendanceId", "/Dashboards/Teacher/Attendance/:attendanceId"],
  ["/teacher/reports", "/Dashboards/Teacher/Reports"],
  ["/teacher/announcements", "/Dashboards/Teacher/Announcements"],
  ["/teacher/announcements/:announcementId", "/Dashboards/Teacher/Announcements/:announcementId"],
  ["/teacher/correction-requests", "/Dashboards/Teacher/CorrectionRequests"],
  ["/teacher/correction-requests/new", "/Dashboards/Teacher/CorrectionRequests/New"],
  ["/teacher/correction-requests/:requestId", "/Dashboards/Teacher/CorrectionRequests/:requestId"],
  ["/teacher/notifications", "/Dashboards/Teacher/Notifications"],
  ["/teacher/profile", "/Dashboards/Teacher/Profile"],
  ["/teacher/profile/security", "/Dashboards/Teacher/Profile/Security"],

  ["/student", "/Dashboards/Student"],
  ["/student/attendance", "/Dashboards/Student/Attendance"],
  ["/student/attendance/:attendanceId", "/Dashboards/Student/Attendance/:attendanceId"],
  ["/student/sms-status", "/Dashboards/Student/SmsStatus"],
  ["/student/announcements", "/Dashboards/Student/Announcements"],
  ["/student/announcements/:announcementId", "/Dashboards/Student/Announcements/:announcementId"],
  ["/student/correction-requests", "/Dashboards/Student/CorrectionRequests"],
  ["/student/correction-requests/new", "/Dashboards/Student/CorrectionRequests/New"],
  ["/student/correction-requests/:requestId", "/Dashboards/Student/CorrectionRequests/:requestId"],
  ["/student/notifications", "/Dashboards/Student/Notifications"],
  ["/student/profile", "/Dashboards/Student/Profile"],
  ["/student/profile/security", "/Dashboards/Student/Profile/Security"],

  ["/api/auth/activity", "/Api/auth/activity"],
  ["/api/rfid/:path*", "/Api/Rfid/:path*"],
  ["/api/students/:path*", "/Api/Students/:path*"],
  ["/api/attendance/:path*", "/Api/Attendance/:path*"],
  ["/api/sms/:path*", "/Api/Sms/:path*"],
  ["/api/reports/:path*", "/Api/Reports/:path*"],
  ["/api/users/:path*", "/Api/Users/:path*"],
  ["/api/announcements/:path*", "/Api/Announcements/:path*"],
  ["/api/correction-requests/:path*", "/Api/CorrectionRequests/:path*"],
  ["/api/notifications/:path*", "/Api/Notifications/:path*"],
  ["/api/audit-logs/:path*", "/Api/AuditLogs/:path*"],
  ["/api/devices/:path*", "/Api/Devices/:path*"],
] as const;

const nextConfig: NextConfig = {
  reactStrictMode: false,
  rewrites() {
    return routeAliases.map(([source, destination]) => ({
      source,
      destination,
    }));
  },
};

export default nextConfig;
